// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ключ приложения AcoustID (теги по звуку) заводит пользователь на
 * acoustid.org/new-application — как и ключ Last.fm: чужой ключ — чужая квота.
 */
export type AcoustidSettings = { apiKey: string | null, };
