// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlbumRow = { key: string, title: string, artist: string | null, year: number | null, trackCount: number, durationMs: number, hasCover: boolean, };
