// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeadphoneProfile } from "./HeadphoneProfile";
import type { ReplayGainMode } from "./ReplayGainMode";

export type AudioSettings = { 
/**
 * `None` — системное устройство по умолчанию.
 */
deviceId: string | null, 
/**
 * Целевое наполнение кольцевого буфера. Больше — устойчивее к пропускам,
 * но дольше отклик EQ (он считается до буфера).
 */
bufferMs: number, replayGain: ReplayGainMode, replayGainPreampDb: number, 
/**
 * 0 — режим gapless, иначе длительность кроссфейда.
 */
crossfadeMs: number, eqEnabled: boolean, eqPreampDb: number, eqBandsDb: Array<number>, 
/**
 * Профиль наушников (AutoEQ) и включён ли он. Профиль хранится и когда
 * выключен — чтобы включить обратно без сети.
 */
headphone: HeadphoneProfile | null, headphoneEnabled: boolean, 
/**
 * Открывать устройство на частоте файла, если оно её поддерживает:
 * звук идёт без пересчёта. Цена — пауза на стыке треков разной частоты.
 */
exactRate: boolean, };
