// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnId } from "./ColumnId";

export type ColumnSetting = { id: ColumnId, width: number | null, };
