// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Что вышло с одним альбомом.
 */
export type CoverFetchResult = { found: boolean, 
/**
 * «iTunes» или «Cover Art Archive».
 */
source: string | null, written: number, failed: number, };
