// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoversProgress = { processed: number, total: number, 
/**
 * «Исполнитель — Альбом», над которым работаем.
 */
current: string, found: number, };
