// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Идентификатор приложения Discord общий и живёт в `discord/`: здесь только
 * выключатель. Старое поле `clientId` в файле настроек просто игнорируется.
 */
export type DiscordSettings = { enabled: boolean, };
