// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryTrack } from "./LibraryTrack";

/**
 * Группа похожих треков. Ключ нужен фронту для `{#each}` и для заголовка.
 */
export type DuplicateGroup = { key: string, tracks: Array<LibraryTrack>, };
