// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileOpResult = { done: number, failed: number, 
/**
 * Причина первой неудачи: показываем её, а не «что-то пошло не так».
 */
message: string | null, };
