// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GainPhase } from "./GainPhase";

export type GainProgress = { phase: GainPhase, processed: number, total: number, 
/**
 * Имя файла, а не путь: в строке прогресса всё равно виден только хвост.
 */
current: string | null, };
