// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeqFilter } from "./PeqFilter";

export type HeadphoneProfile = { 
/**
 * Модель, как она названа в базе AutoEQ или в имени файла.
 */
name: string, 
/**
 * Кто измерял (oratory1990, crinacle…) — у одной модели бывает несколько.
 */
source: string, preampDb: number, filters: Array<PeqFilter>, };
