// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Модель в базе. У популярной их несколько — от разных измерителей.
 */
export type HeadphoneHit = { name: string, 
/**
 * «oratory1990», «crinacle on GRAS 43AG-7».
 */
source: string, 
/**
 * Путь внутри results/, уже с процентами — как в индексе.
 */
path: string, };
