// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ключ и секрет приложения Last.fm заводит сам пользователь: чужой ключ в
 * плеере — это чужая квота и чужая ответственность.
 */
export type LastfmSettings = { enabled: boolean, apiKey: string | null, apiSecret: string | null, 
/**
 * Ключ сессии: постоянный, отзывается на сайте Last.fm.
 */
sessionKey: string | null, username: string | null, };
