// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibrarySettings = { folders: Array<string>, watch: boolean, followSymlinks: boolean, 
/**
 * При запуске сверять плейлисты с их папками-источниками.
 */
refreshPlaylists: boolean, };
