// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibraryTrack = { id: number, path: string, title: string, artist: string | null, album: string | null, year: number | null, trackNo: number | null, durationMs: number | null, playCount: number, 
/**
 * 0 — без оценки, иначе 1..5.
 */
rating: number, 
/**
 * Когда слушали в последний раз, unix-время. `None` — ни разу.
 */
lastPlayed: number | null, };
