// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatsBucket } from "./StatsBucket";
import type { StatsEntry } from "./StatsEntry";

export type ListeningStats = { plays: number, listenedMs: number, tracks: number, artists: number, topArtists: Array<StatsEntry>, topTracks: Array<StatsEntry>, topAlbums: Array<StatsEntry>, buckets: Array<StatsBucket>, 
/**
 * Прослушивания по часам суток (местное время), 24 числа.
 */
byHour: Array<number>, };
