// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LyricsFinished = { found: number, 
/**
 * Текст уже был — в файле рядом или в теге.
 */
skipped: number, 
/**
 * В базе нет текста (или это инструментал).
 */
missing: number, failed: number, cancelled: boolean, };
