// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LyricLine = { 
/**
 * Момент, с которого строка звучит. `None` — текст без синхронизации.
 */
atMs: number | null, text: string, };
