// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LyricLine } from "./LyricLine";

export type Lyrics = { lines: Array<LyricLine>, 
/**
 * Есть метки времени — можно подсвечивать строку по позиции.
 */
synced: boolean, 
/**
 * Текст взят из файла `.lrc`, а не из тега.
 */
fromFile: boolean, };
