// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lyrics } from "./Lyrics";
import type { LyricsFetchStatus } from "./LyricsFetchStatus";

export type LyricsFetch = { status: LyricsFetchStatus, lyrics: Lyrics | null, 
/**
 * Текст лёг файлом рядом с треком: значит найдётся и в следующий раз, и
 * другими плеерами тоже.
 */
saved: boolean, 
/**
 * Как трек назван в базе. Если нашлось не то, это видно сразу.
 */
matched: string | null, };
