// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LyricsProgress = { processed: number, total: number, 
/**
 * Имя файла: в строке прогресса всё равно виден только хвост.
 */
current: string | null, found: number, };
