// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Чем закончился поиск текста в интернете.
 */
export type LyricsFetchStatus = "found" | "instrumental" | "missing" | "noTags";
