// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NamedCount = { name: string, tracks: number, 
/**
 * Для исполнителей — число альбомов, для остальных 0.
 */
albums: number, };
