// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterShape } from "./FilterShape";

export type PeqFilter = { shape: FilterShape, frequency: number, gainDb: number, q: number, };
