// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Источники одного списка — для диалога.
 */
export type PlaylistSources = { sources: Array<string>, 
/**
 * Сколько файлов из этих папок убрано руками и не вернётся при обновлении.
 */
excluded: number, };
