// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistSort } from "./PlaylistSort";
import type { PlaylistTab } from "./PlaylistTab";

export type PlaylistMeta = { count: number, currentIndex: number | null, sort: PlaylistSort, 
/**
 * Растёт при любом изменении: фронт по нему понимает, что окно пора перечитать.
 */
version: number, totalDurationMs: number, tabs: Array<PlaylistTab>, 
/**
 * Сколько строк ждёт своей очереди.
 */
queued: number, };
