// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistRow } from "./PlaylistRow";

/**
 * Результат поиска: строки одной страницы и сколько нашлось всего.
 */
export type PlaylistSearch = { total: number, rows: Array<PlaylistRow>, };
