// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Строка для таблицы. Отдельный тип: во фронт уезжает `String`, а не `PathBuf`,
 * и добавляется индекс, который во фронте считать неоткуда.
 */
export type PlaylistRow = { index: number, id: number, path: string, title: string, artist: string | null, album: string | null, trackNo: number | null, durationMs: number | null, metaLoaded: boolean, isCurrent: boolean, 
/**
 * Трек внутри общего файла (CUE) — для него не показываем путь как имя.
 */
isRegion: boolean, year: number | null, genre: string | null, bitrateKbps: number | null, sampleRate: number | null, 
/**
 * Из библиотеки — у файлов вне её `None`.
 */
playCount: number | null, rating: number | null, };
