// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Вкладка для панели плейлистов.
 */
export type PlaylistTab = { id: number, name: string, count: number, isActive: boolean, 
/**
 * Из этого списка сейчас играет музыка — он может быть не тем, что открыт.
 */
isPlaying: boolean, 
/**
 * Вкладка «Открытые файлы»: временная очередь, а не собранный список.
 */
isTemporary: boolean, 
/**
 * Сколько папок-источников у списка; 0 — собран руками.
 */
sources: number, };
