// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepeatMode } from "./RepeatMode";

/**
 * Как слушают конкретный список. Повтор и перемешивание — свойство списка,
 * а не плеера: вернувшись к плейлисту, хочется продолжить так же, как его
 * слушали в прошлый раз.
 */
export type PlaybackMode = { repeat: RepeatMode, shuffle: boolean, };
