// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybackStatus } from "./PlaybackStatus";
import type { TrackInfo } from "./TrackInfo";

export type PlayerState = { status: PlaybackStatus, positionMs: number, durationMs: number, volume: number, track: TrackInfo | null, 
/**
 * Имя устройства, на котором реально открыт поток.
 */
device: string | null, 
/**
 * Частота, на которой открыт поток устройства; 0 — не открыт. Отличается
 * от частоты трека — значит, звук пересчитывается.
 */
deviceRate: number, };
