// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Что с частотой: на какой открыто устройство, какие оно умеет и может ли
 * плеер разрешить PipeWire другие.
 */
export type RateStatus = { exact: boolean, 
/**
 * Частота играющего трека; `None` — ничего не играет.
 */
trackRate: number | null, 
/**
 * 0 — устройство не открыто.
 */
deviceRate: number, 
/**
 * Частоты, на которых устройство откроется без пересчёта.
 */
supported: Array<number>, 
/**
 * Плеер умеет менять частоты PipeWire (Linux и `pw-metadata`).
 */
canManage: boolean, 
/**
 * Разрешение выдано плеером — лежит его фрагмент настроек.
 */
managed: boolean, };
