// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Строка предпросмотра: что во что превратится и почему не превратится.
 */
export type RenamePreview = { from: string, to: string, problem: string | null, };
