// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanPhase } from "./ScanPhase";

export type ScanProgress = { phase: ScanPhase, processed: number, 
/**
 * 0, пока общее число файлов ещё неизвестно (фаза обхода).
 */
total: number, current: string | null, };
