// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcoustidSettings } from "./AcoustidSettings";
import type { AudioSettings } from "./AudioSettings";
import type { DiscordSettings } from "./DiscordSettings";
import type { LastfmSettings } from "./LastfmSettings";
import type { LibrarySettings } from "./LibrarySettings";
import type { PlaybackSettings } from "./PlaybackSettings";
import type { SmartList } from "./SmartList";
import type { UiSettings } from "./UiSettings";

export type Settings = { version: number, playback: PlaybackSettings, audio: AudioSettings, library: LibrarySettings, ui: UiSettings, lastfm: LastfmSettings, discord: DiscordSettings, acoustid: AcoustidSettings, 
/**
 * Умные списки, собранные пользователем. Встроенные живут во фронте:
 * это те же правила, просто неизменяемые.
 */
smartLists: Array<SmartList>, };
