// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Что просят из интерфейса.
 */
export type SleepRequest = { "kind": "off" } | { "kind": "minutes", minutes: number, } | { "kind": "afterTrack" };
