// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SleepKind } from "./SleepKind";

/**
 * Состояние для интерфейса. Обратный отсчёт фронт ведёт сам от `remaining_ms`.
 */
export type SleepState = { kind: SleepKind, remainingMs: number | null, };
