// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmartField = "title" | "artist" | "album" | "genre" | "year" | "rating" | "playCount" | "lastPlayed" | "addedAt" | "duration" | "folder";
