// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmartRule } from "./SmartRule";
import type { SmartSort } from "./SmartSort";

export type SmartRules = { 
/**
 * Все условия должны совпасть: «или» в жизни почти не нужно, а вид
 * правил усложняет заметно.
 */
rules: Array<SmartRule>, sort: SmartSort, descending: boolean, limit: number | null, };
