// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmartRules } from "./SmartRules";

export type SmartList = { id: number, name: string, rules: SmartRules, };
