// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmartField } from "./SmartField";
import type { SmartOp } from "./SmartOp";

export type SmartRule = { field: SmartField, op: SmartOp, value: string, };
