// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SortKey = "manual" | "title" | "artist" | "album" | "duration" | "trackNo" | "path" | "year" | "genre" | "bitrate";
