// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Итог обновления по источникам.
 */
export type SourcesRefresh = { added: number, removed: number, 
/**
 * Папки, до которых не достали: их строки оставлены как были.
 */
unreachable: Array<string>, };
