// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatsBucket = { 
/**
 * `2026-10-01` или `2026-10`.
 */
label: string, plays: number, listenedMs: number, };
