// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatsEntry = { name: string, 
/**
 * Исполнитель — у треков и альбомов.
 */
detail: string | null, 
/**
 * Путь — у треков: из итогов трек можно включить.
 */
path: string | null, plays: number, listenedMs: number, };
