// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Вариант тегов для файла.
 */
export type TagCandidate = { 
/**
 * Насколько отпечаток совпал, 0…1.
 */
score: number, title: string, artist: string, album: string | null, 
/**
 * Исполнитель альбома, если он не тот же, что у трека (сборники).
 */
albumArtist: string | null, year: number | null, track: number | null, trackTotal: number | null, 
/**
 * Номер диска — только у многодисковых изданий.
 */
disk: number | null, 
/**
 * «Альбом», «Сингл», «Сборник» — чтобы было видно, что выбираешь.
 */
kind: string | null, releaseGroupId: string | null, };
