// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Что записать в теги.
 *
 * `None` — поле не трогаем (в групповой правке так выглядит «у файлов
 * разные значения, оставить как есть»). Пустая строка и ноль — **удалить**
 * тег: иначе не было бы способа стереть чужой мусор из поля.
 */
export type TagEdit = { title: string | null, artist: string | null, album: string | null, albumArtist: string | null, genre: string | null, comment: string | null, year: number | null, track: number | null, trackTotal: number | null, disk: number | null, };
