// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Итог групповой правки. Один битый файл не должен отменять правку
 * остальных, поэтому считаем и то, и другое.
 */
export type TagWriteResult = { written: number, failed: number, 
/**
 * Причина первой неудачи — её и показываем пользователю.
 */
message: string | null, };
