// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackInfo = { 
/**
 * Строка плейлиста, из которой пришёл трек. 0 — трек не из плейлиста.
 */
itemId: number, 
/**
 * Кусок внутри общего файла (CUE): теги файла к нему не относятся.
 */
isRegion: boolean, path: string, 
/**
 * Пока это имя файла: разбор тегов появится на шаге с lofty.
 */
title: string, durationMs: number | null, sampleRate: number, channels: number, codec: string, };
