// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackTags = { title: string | null, artist: string | null, album: string | null, albumArtist: string | null, genre: string | null, year: number | null, track: number | null, trackTotal: number | null, disk: number | null, comment: string | null, durationMs: number, bitrateKbps: number | null, sampleRate: number | null, channels: number | null, 
/**
 * MIME обложки. `None` — обложки в файле нет, за картинкой можно не ходить.
 */
coverMime: string | null, 
/**
 * В файле есть текст песни. Сам текст приезжает отдельной командой:
 * в теги он попадает целыми куплетами, и таскать их в каждой строке
 * плейлиста незачем.
 */
hasLyrics: boolean, };
