// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnSetting } from "./ColumnSetting";
import type { MainView } from "./MainView";
import type { TabLayout } from "./TabLayout";
import type { Theme } from "./Theme";

export type UiSettings = { theme: Theme, minimizeToTray: boolean, 
/**
 * Раздел, открытый при прошлом закрытии окна.
 */
view: MainView, 
/**
 * Показывать системное уведомление при смене трека.
 */
trackNotifications: boolean, 
/**
 * Компактный режим: одна полоса плеера вместо всего окна.
 */
mini: boolean, 
/**
 * Держать окно поверх остальных.
 */
alwaysOnTop: boolean, 
/**
 * Цвет акцента, `#rrggbb`. `None` — из темы.
 */
accent: string | null, 
/**
 * Акцент берётся из обложки играющего трека; `accent` — запасной, для
 * треков без обложки или с бесцветной.
 */
accentFromCover: boolean, 
/**
 * Основной размер шрифта в пикселях; остальные размеры и высота строк
 * списков считаются от него.
 */
fontSize: number, 
/**
 * Шрифт интерфейса: встроенный по ключу (`system`, `inter`…) или имя
 * установленного в системе семейства.
 */
font: string, 
/**
 * Шрифт текста песни — так же.
 */
lyricsFont: string, 
/**
 * Колонки плейлиста по порядку; ширина `None` — по умолчанию.
 */
playlistColumns: Array<ColumnSetting>, 
/**
 * Плейлисты вкладками сверху или списком слева.
 */
tabLayout: TabLayout, 
/**
 * Ширина колонки плейлистов и свёрнута ли она в узкую полосу.
 */
sidebarWidth: number, sidebarCollapsed: boolean, };
